{
  "hash": "c0e1d41031dc90cc7e7e823977ce34f5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Sophia Meyers\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\n**In this analysis, I examine median gross rent across counties in Oregon. I want to understand which communities have the most and least reliable rent estimates and whether some counties have greater uncertainty in their Census data than others.**\n\n---\n\n## Choosing what to measure\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"OR\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25064_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                     variable   estimate   moe\n  <chr> <chr>                    <chr>         <dbl> <dbl>\n1 41001 Baker County, Oregon     B25064_001      814    38\n2 41003 Benton County, Oregon    B25064_001     1359    41\n3 41005 Clackamas County, Oregon B25064_001     1693    21\n4 41007 Clatsop County, Oregon   B25064_001     1130    40\n5 41009 Columbia County, Oregon  B25064_001     1221    68\n6 41011 Coos County, Oregon      B25064_001      992    41\n```\n\n\n:::\n:::\n\n\n\n**I got 36 rows back, which is the total amount of counties in Oregon.**\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                      estimate   moe moe_pct\n   <chr>                        <dbl> <dbl>   <dbl>\n 1 Gilliam County, Oregon        1084   166   15.3 \n 2 Sherman County, Oregon         945   133   14.1 \n 3 Wheeler County, Oregon         782   105   13.4 \n 4 Morrow County, Oregon          910   109   12.0 \n 5 Hood River County, Oregon     1381   148   10.7 \n 6 Crook County, Oregon          1224   122    9.97\n 7 Wallowa County, Oregon         858    76    8.86\n 8 Curry County, Oregon          1156   102    8.82\n 9 Lake County, Oregon            861    75    8.71\n10 Jefferson County, Oregon       957    72    7.52\n```\n\n\n:::\n:::\n\n\n\n**Gilliam County, Oregon has the largest margin of error relative to its estimate? It is 15.313653%**\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    20\n2 Low confidence      5\n3 Moderate           11\n```\n\n\n:::\n:::\n\n\n\n**20 counties fall into high confidence, 5 fall into low confidence, and 11 fall into moderate.**\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                     myvarE myvarM   popE  popM\n  <chr> <chr>                     <dbl>  <dbl>  <dbl> <dbl>\n1 41001 Baker County, Oregon        814     38  16796    NA\n2 41003 Benton County, Oregon      1359     41  96359    NA\n3 41005 Clackamas County, Oregon   1693     21 422308    NA\n4 41007 Clatsop County, Oregon     1130     40  41343    NA\n5 41009 Columbia County, Oregon    1221     68  53178    NA\n6 41011 Coos County, Oregon         992     41  64832    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         20        197743.\n2 Low confidence           1          2002 \n3 Moderate                15         18790.\n```\n\n\n:::\n:::\n\n\n\n**High confidence counties have an average population of about 197,743, while moderate confidence counties average about 18,790 people. The one low confidence county has a much smaller population of about 2,002 people. The results show that smaller counties tend to have less reliable estimates and larger margins of error.**\n\n---\n\n## What this means for policy\n\n**The communities we know the least about in this analysis are the smaller counties in Oregon, which have the largest margins of error relative to their median gross rent estimates. Gilliam County has the highest margin of error at 15.31%, followed by Sherman County at 14.07% and Wheeler County at 13.43%. Morrow County and Hood River County also have relatively high margins of error, at 11.98% and 10.72%, respectively. These results suggest that the reliability of ACS estimates is related to the size of the communities being measured. The ACS does not collect information from every household. It uses a sample to estimate characteristics for larger populations. There are fewer households in smaller counties to be included in the sample, meaning that individual responses have a greater effect on the overall estimate. This causes larger margins of error for the reported median gross rent. \nThe high-confidence counties in my analysis have an average population of about 197,743, compared with only 18,790 for moderate-confidence counties and 2,002 for the one low-confidence county. This uncertainty could create problems if a state agency used these estimates to allocate housing-related funding while treating every county's number as equally reliable. Smaller counties could receive too much or too little funding based on an estimate that is relatively uncertain. This could particularly hurt rural communities, such as in Gillian County, where limited resources and smaller populations already make it harder to accurately identify housing needs.**\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}